---
- name: Configuration Database Server
  hosts: db-01

  user: vagrant
  become: yes
  vars_files:
    - vars/main.yaml
  vars:
    - dbname: "db01"
    - dbusername: "root"
    - dbpassword: "123456"
  tasks:
    - name: Configure hosts ansible
      lineinfile: 
        dest: /etc/hosts
        state: present
        line: "{{item}}"
      with_items:
        - 192.168.56.2 control-node
        - 192.168.56.3 app-01
        - 192.168.56.4 db-01
  roles:
    - configuration-default-so
    - role: geerlingguy.mysql


